### ISSUE TITLE
Linear instead of sinusoidal?

### ISSUE THREAD

**Issue by rcrowe-google** [google-research/perceiver-ar#12]
Should this instead be "1D Linear Position Embedding Initializer"

https://github.com/google-research/perceiver-ar/blob/72504d370dd1236abd491e37c5295566cc1dbc64/perceiver_ar/perceiver_ar_model.py#L149

**Comment by cghawthorne** [comment]
Good catch! We didn't actually use this type of position encoding for the paper, but they might be useful for debugging, so it's good to have the description be accurate.
