### ISSUE TITLE
Unable to perform training perceiver-ar

### ISSUE THREAD

**Issue by gyokuro33** [google-research/perceiver-ar#4]
If I follow the steps in the ReadMe, I get the following error when training the model.

```
HONPATH python experiment.py  --config=experiment.py:random_mirrored_32
Traceback (most recent call last):
  File "experiment.py", line 29, in <module>
    from perceiver_ar import dataset
ModuleNotFoundError: No module named 'perceiver_ar'
```

**Comment by gyokuro33** [comment]
> PYTHONPATH=.::$PYTHONPATH python experiment.py  --config=experiment.py:random_mirrored_32

NO.
I typed the same command as in the previous example, but it was displayed as follows.

```
 PYTHONPATH=.::$PYTHONPATH python experiment.py  --config=experiment.py:random_mirrored_32
Traceback (most recent call last):
  File "experiment.py", line 29, in <module>
    from perceiver_ar import dataset
ModuleNotFoundError: No module named 'perceiver_ar'
```

**Comment by cghawthorne** [comment]
Apologies for not looking into this more earlier, I was offline for a while. I see the problem with the paths in the README now and will fix shortly.
