### ISSUE TITLE
Pretrained model?

### ISSUE THREAD

**Issue by mattolson93** [google-research/perceiver-ar#9]
Is there anywhere I can download the pretrained models?

**Comment by ArEnSc** [comment]
same!

**Comment by cghawthorne** [comment]
The copy task checkpoint and instructions on how to use it are in the inference notebook. I'm unfortunately having some XLA compilation issues with some of the other checkpoints in the open source environment but hope to make them available soon too. Is there a particular one you were most interested in?

**Comment by mattolson93** [comment]
In particular, I'd like the MAESTRO v3 Symbolic model (every other MIDI-based model is old these days). 

Thanks!

**Comment by ArEnSc** [comment]
@cghawthorne I read the paper I was looking for a language generation model if possible, not sure if you guys are planning on that  thanks! I will have to find a pytorch implementation any how =)

**Comment by cghawthorne** [comment]
Quick update here: unfortunately there are some differences between the internal JAX/XLA infrastructure and the external version that are preventing the larger models from compiling properly in open source. I'm working with the JAX team to try to get this resolved, but it may take a while.

**Comment by VladPetk** [comment]
> In particular, I'd like the MAESTRO v3 Symbolic model (every other MIDI-based model is old these days).
> 
> Thanks!

Hey, not sure if this is relevant for you, but [someone wrote a script](https://github.com/feizc/Perceiver-Music-Generation) to train the[ PyTorch implementation of Perceiver AR](https://github.com/lucidrains/perceiver-ar-pytorch) on the Maestro 2.0 dataset (should be easily adaptable to 3.0). I'm currently testing it now, and it seems to work quite well.

**Comment by mattolson93** [comment]
> Hey, not sure if this is relevant for you, but [someone wrote a script](https://github.com/feizc/Perceiver-Music-Generation) to train the[ PyTorch implementation of Perceiver AR](https://github.com/lucidrains/perceiver-ar-pytorch) on the Maestro 2.0 dataset (should be easily adaptable to 3.0). I'm currently testing it now, and it seems to work quite well.

Thanks for the pointer! This should work for me.
